# Generated by Django 5.0.4 on 2024-04-05 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrival_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
