# Generated by Django 5.0.4 on 2024-04-05 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_order_arrival_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='arrival_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
